In [66]:
import pandas as pd

In [67]:
import glob

In [68]:
path = "C:/Users/Spencer Woo/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data/Daily_Snow_Observations_Data_2024"

In [69]:
all_files = glob.glob(path + "/*.csv")

In [70]:
li = []

In [71]:
##read_csv has lots of arguments to direct how the data is read into the dataframe, ex delimiter and date format.

In [72]:
for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0, comment="#", on_bad_lines='skip')
    li.append(df[df["Station Name"]=="SNOWSHOE"])

KeyError: 'Station Name'

In [73]:
# df will only hold the most recent csv to be read into the dataframe because it is being used in the for loop
# I have to concatenate all rows in li to receive the complete dataset

In [74]:
frame = pd.concat(li, axis=0, ignore_index=True)

In [75]:
frame

,GHCN ID,Station Name,County,State,Elevation,Latitude,Longitude,Nov 1,Nov 2,Nov 3,Nov 4,Nov 5,Nov 6,Nov 7,Nov 8,Nov 9,Nov 10,Nov 11,Nov 12,Nov 13,Nov 14,Nov 15,Nov 16,Nov 17,Nov 18,Nov 19,Nov 20,Nov 21,Nov 22,Nov 23,Nov 24,Nov 25,Nov 26,Nov 27,Nov 28,Nov 29,Nov 30,Dec 1,Dec 2,Dec 3,Dec 4,Dec 5,Dec 6,Dec 7,Dec 8,Dec 9,Dec 10,Dec 11,Dec 12,Dec 13,Dec 14,Dec 15,Dec 16,Dec 17,Dec 18,Dec 19,Dec 20,Dec 21,Dec 22,Dec 23,Dec 24,Dec 25,Dec 26,Dec 27,Dec 28,Dec 29,Dec 30,Dec 31,Jan 1,Jan 2,Jan 3,Jan 4,Jan 5,Jan 6,Jan 7,Jan 8,Jan 9,Jan 10,Jan 11,Jan 12,Jan 13,Jan 14,Jan 15,Jan 16,Jan 17,Jan 18,Jan 19,Jan 20,Jan 21,Jan 22,Jan 23,Jan 24,Jan 25,Jan 26,Jan 27,Jan 28,Jan 29,Jan 30,Jan 31,Feb 1,Feb 2,Feb 3,Feb 4,Feb 5,Feb 6,Feb 7,Feb 8,Feb 9,Feb 10,Feb 11,Feb 12,Feb 13,Feb 14,Feb 15,Feb 16,Feb 17,Feb 18,Feb 19,Feb 20,Feb 21,Feb 22,Feb 23,Feb 24,Feb 25,Feb 26,Feb 27,Feb 28,Mar 1,Mar 2,Mar 3,Mar 4,Mar 5,Mar 6,Mar 7,Mar 8,Mar 9,Mar 10,Mar 11,Mar 12,Mar 13,Mar 14,Mar 15,Mar 16,Mar 17,Mar 18,Mar 19,Mar 20,Mar 21,Mar 22,Mar 23,Mar 24,Mar 25,Mar 26,Mar 27,Mar 28,Mar 29,Mar 30,Mar 31
0,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1,1,0,2.5,1,0.5,0,M,M,M,3.8,M,0,M,4,M,M,M,1,2.1,3.1,0,0,M,M,M,M,M,M,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
frame.drop_duplicates(inplace=True)

In [77]:
pd.set_option('display.max_rows', None)

In [78]:
pd.set_option('display.max_columns', None)

In [79]:
frame

,GHCN ID,Station Name,County,State,Elevation,Latitude,Longitude,Nov 1,Nov 2,Nov 3,Nov 4,Nov 5,Nov 6,Nov 7,Nov 8,Nov 9,Nov 10,Nov 11,Nov 12,Nov 13,Nov 14,Nov 15,Nov 16,Nov 17,Nov 18,Nov 19,Nov 20,Nov 21,Nov 22,Nov 23,Nov 24,Nov 25,Nov 26,Nov 27,Nov 28,Nov 29,Nov 30,Dec 1,Dec 2,Dec 3,Dec 4,Dec 5,Dec 6,Dec 7,Dec 8,Dec 9,Dec 10,Dec 11,Dec 12,Dec 13,Dec 14,Dec 15,Dec 16,Dec 17,Dec 18,Dec 19,Dec 20,Dec 21,Dec 22,Dec 23,Dec 24,Dec 25,Dec 26,Dec 27,Dec 28,Dec 29,Dec 30,Dec 31,Jan 1,Jan 2,Jan 3,Jan 4,Jan 5,Jan 6,Jan 7,Jan 8,Jan 9,Jan 10,Jan 11,Jan 12,Jan 13,Jan 14,Jan 15,Jan 16,Jan 17,Jan 18,Jan 19,Jan 20,Jan 21,Jan 22,Jan 23,Jan 24,Jan 25,Jan 26,Jan 27,Jan 28,Jan 29,Jan 30,Jan 31,Feb 1,Feb 2,Feb 3,Feb 4,Feb 5,Feb 6,Feb 7,Feb 8,Feb 9,Feb 10,Feb 11,Feb 12,Feb 13,Feb 14,Feb 15,Feb 16,Feb 17,Feb 18,Feb 19,Feb 20,Feb 21,Feb 22,Feb 23,Feb 24,Feb 25,Feb 26,Feb 27,Feb 28,Mar 1,Mar 2,Mar 3,Mar 4,Mar 5,Mar 6,Mar 7,Mar 8,Mar 9,Mar 10,Mar 11,Mar 12,Mar 13,Mar 14,Mar 15,Mar 16,Mar 17,Mar 18,Mar 19,Mar 20,Mar 21,Mar 22,Mar 23,Mar 24,Mar 25,Mar 26,Mar 27,Mar 28,Mar 29,Mar 30,Mar 31
0,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1,1,0,2.5,1,0.5,0,M,M,M,3.8,M,0,M,4,M,M,M,1,2.1,3.1,0,0,M,M,M,M,M,M,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.7,2.5,1,2,0,6.6,3.7,2,4,1.2,3,6,T,0,1,0,2,0,1,6,0.5,0,0,1,0,0,1,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,M,1,0,1,0,7,M,3.5,0,0,10,0,1,2,2,0,0,0,0,0,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.4,0,0,0,0.5,2,1,1,0,0,0,0,0,0,0,0.5,0,0,0,2.5,0,0,0,0,2,T,0,0,0,0

In [33]:
frame.groupby('GHCN ID')

In [1]:
pd.reset_option('display.max_rows')

NameError: name 'pd' is not defined

In [17]:
frame = pd.melt(frame, id_vars=['GHCN ID'], var_name='Date', value_name='Station')

In [386]:
frame.to_csv('C:/Users/Spencer Woo/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data/pocahontas_county_WV_snowfall_2024.csv', index=False)

In [46]:
frame

Dec 1        1
Dec 2        1
Dec 3        0
Dec 4      2.5
Dec 5        1
Dec 6      0.5
Dec 7        0
Dec 8        M
Dec 9        M
Dec 10       M
Dec 11     3.8
Dec 12       M
Dec 13       0
Dec 14       M
Dec 15       4
Dec 16       M
Dec 17       M
Dec 18       M
Dec 19       1
Dec 20     2.1
Dec 21     3.1
Dec 22       0
Dec 23       0
Dec 24       M
Dec 25       M
Dec 26       M
Dec 27       M
Dec 28       M
Dec 29       M
Dec 30    None
Name: 30, dtype: object

In [60]:
frame.iloc[1, 37]

'4'

In [61]:
frame.iloc[1, 67]

'M'

In [95]:
frame.loc[4: 'Mar 1'].shift(periods=-1)

,GHCN ID,Station Name,County,State,Elevation,Latitude,Longitude,Nov 1,Nov 2,Nov 3,Nov 4,Nov 5,Nov 6,Nov 7,Nov 8,Nov 9,Nov 10,Nov 11,Nov 12,Nov 13,Nov 14,Nov 15,Nov 16,Nov 17,Nov 18,Nov 19,Nov 20,Nov 21,Nov 22,Nov 23,Nov 24,Nov 25,Nov 26,Nov 27,Nov 28,Nov 29,Nov 30,Dec 1,Dec 2,Dec 3,Dec 4,Dec 5,Dec 6,Dec 7,Dec 8,Dec 9,Dec 10,Dec 11,Dec 12,Dec 13,Dec 14,Dec 15,Dec 16,Dec 17,Dec 18,Dec 19,Dec 20,Dec 21,Dec 22,Dec 23,Dec 24,Dec 25,Dec 26,Dec 27,Dec 28,Dec 29,Dec 30,Dec 31,Jan 1,Jan 2,Jan 3,Jan 4,Jan 5,Jan 6,Jan 7,Jan 8,Jan 9,Jan 10,Jan 11,Jan 12,Jan 13,Jan 14,Jan 15,Jan 16,Jan 17,Jan 18,Jan 19,Jan 20,Jan 21,Jan 22,Jan 23,Jan 24,Jan 25,Jan 26,Jan 27,Jan 28,Jan 29,Jan 30,Jan 31,Feb 1,Feb 2,Feb 3,Feb 4,Feb 5,Feb 6,Feb 7,Feb 8,Feb 9,Feb 10,Feb 11,Feb 12,Feb 13,Feb 14,Feb 15,Feb 16,Feb 17,Feb 18,Feb 19,Feb 20,Feb 21,Feb 22,Feb 23,Feb 24,Feb 25,Feb 26,Feb 27,Feb 28,Mar 1,Mar 2,Mar 3,Mar 4,Mar 5,Mar 6,Mar 7,Mar 8,Mar 9,Mar 10,Mar 11,Mar 12,Mar 13,Mar 14,Mar 15,Mar 16,Mar 17,Mar 18,Mar 19,Mar 20,Mar 21,Mar 22,Mar 23,Mar 24,Mar 25,Mar 26,Mar 27,Mar 28,Mar 29,Mar 30,Mar 31
30,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801.0,38.4,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.7,2.5,1,2,0,6.6,3.7,2,4,1.2,3,6,T,0,1,0,2,0,1,6,0.5,0,0,1,0,0,1,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801.0,38.4,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,M,1,0,1,0,7,M,3.5,0,0,10,0,1,2,2,0,0,0,0,0,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801.0,38.4,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.4,0,0,0,0.5,2,1,1,0,0,0,0,0,0,0,0.5,0,0,0,2.5,0,0,0,0,2,T,0,0,0,0
119,None,None,None,None,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [100]:
frame

,GHCN ID,Station Name,County,State,Elevation,Latitude,Longitude,Nov 1,Nov 2,Nov 3,Nov 4,Nov 5,Nov 6,Nov 7,Nov 8,Nov 9,Nov 10,Nov 11,Nov 12,Nov 13,Nov 14,Nov 15,Nov 16,Nov 17,Nov 18,Nov 19,Nov 20,Nov 21,Nov 22,Nov 23,Nov 24,Nov 25,Nov 26,Nov 27,Nov 28,Nov 29,Nov 30,Dec 1,Dec 2,Dec 3,Dec 4,Dec 5,Dec 6,Dec 7,Dec 8,Dec 9,Dec 10,Dec 11,Dec 12,Dec 13,Dec 14,Dec 15,Dec 16,Dec 17,Dec 18,Dec 19,Dec 20,Dec 21,Dec 22,Dec 23,Dec 24,Dec 25,Dec 26,Dec 27,Dec 28,Dec 29,Dec 30,Dec 31,Jan 1,Jan 2,Jan 3,Jan 4,Jan 5,Jan 6,Jan 7,Jan 8,Jan 9,Jan 10,Jan 11,Jan 12,Jan 13,Jan 14,Jan 15,Jan 16,Jan 17,Jan 18,Jan 19,Jan 20,Jan 21,Jan 22,Jan 23,Jan 24,Jan 25,Jan 26,Jan 27,Jan 28,Jan 29,Jan 30,Jan 31,Feb 1,Feb 2,Feb 3,Feb 4,Feb 5,Feb 6,Feb 7,Feb 8,Feb 9,Feb 10,Feb 11,Feb 12,Feb 13,Feb 14,Feb 15,Feb 16,Feb 17,Feb 18,Feb 19,Feb 20,Feb 21,Feb 22,Feb 23,Feb 24,Feb 25,Feb 26,Feb 27,Feb 28,Mar 1,Mar 2,Mar 3,Mar 4,Mar 5,Mar 6,Mar 7,Mar 8,Mar 9,Mar 10,Mar 11,Mar 12,Mar 13,Mar 14,Mar 15,Mar 16,Mar 17,Mar 18,Mar 19,Mar 20,Mar 21,Mar 22,Mar 23,Mar 24,Mar 25,Mar 26,Mar 27,Mar 28,Mar 29,Mar 30,Mar 31
0,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.8,6.3,0,0,0,0,0,2.8,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1,1,0,2.5,1,0.5,0,M,M,M,3.8,M,0,M,4,M,M,M,1,2.1,3.1,0,0,M,M,M,M,M,M,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.7,2.5,1,2,0,6.6,3.7,2,4,1.2,3,6,T,0,1,0,2,0,1,6,0.5,0,0,1,0,0,1,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,M,1,0,1,0,7,M,3.5,0,0,10,0,1,2,2,0,0,0,0,0,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.4,0,0,0,0.5,2,1,1,0,0,0,0,0,0,0,0.5,0,0,0,2.5,0,0,0,0,2,T,0,0,0,0

In [406]:
li

[         GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],

In [394]:
frame.columns

Index(['GHCN ID', 'Station Name', 'County', 'State', 'Elevation', 'Latitude',
       'Longitude', 'Nov 1', 'Nov 2', 'Nov 3',
       ...
       'Feb 19', 'Feb 20', 'Feb 21', 'Feb 22', 'Feb 23', 'Feb 24', 'Feb 25',
       'Feb 26', 'Feb 27', 'Feb 28'],
      dtype='object', length=127)