In [21]:
import pandas as pd

In [22]:
import glob

In [23]:
path = "C:/Users/Spencer Woo/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data/Daily_Snow_Observations_Data_2024"

In [24]:
all_files = glob.glob(path + "/*.csv")

In [25]:
li = []

In [ ]:
##read_csv has lots of arguments to direct how the data is read into the dataframe, ex delimiter and date format.

In [26]:
for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0, comment="#", on_bad_lines='skip')
    li.append(df[df["Station Name"]=="SNOWSHOE"])

KeyError: 'Station Name'

In [27]:
# df will only hold the most recent csv to be read into the dataframe because it is being used in the for loop
# I have to concatenate all rows in li to receive the complete dataset

In [28]:
frame = pd.concat(li, axis=0, ignore_index=True)

In [30]:
frame

,GHCN ID,Station Name,County,State,Elevation,Latitude,Longitude,Nov 1,Nov 2,Nov 3,...,Mar 22,Mar 23,Mar 24,Mar 25,Mar 26,Mar 27,Mar 28,Mar 29,Mar 30,Mar 31
0,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,0,0,0,0,2,T,0,0,0,0
120,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,0,0,0,0,2,T,0,0,0,0
121,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,0,0,0,0,2,T,0,0,0,0
122,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,0,0,0,0,2,T,0,0,0,0
123,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,0,0,0,0,2,T,0,0,0,0
124,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,0,0,0,0,2,T,0,0,0,0
125,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,0,0,0,0,2,T,0,0,0,0
126,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,0,0,0,0,2,T,0,0,0,0

In [31]:
frame.drop_duplicates(inplace=True)

In [32]:
frame

,GHCN ID,Station Name,County,State,Elevation,Latitude,Longitude,Nov 1,Nov 2,Nov 3,...,Mar 22,Mar 23,Mar 24,Mar 25,Mar 26,Mar 27,Mar 28,Mar 29,Mar 30,Mar 31
0,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,0,0,0,0,2,T,0,0,0,0

In [33]:
frame.groupby('GHCN ID')

In [19]:
pd.set_option('display.max_rows', None)

In [ ]:
pd.reset_option('display.max_rows')

In [17]:
frame = pd.melt(frame, id_vars=['GHCN ID'], var_name='Date', value_name='Station')

In [386]:
frame.to_csv('C:/Users/Spencer Woo/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data/pocahontas_county_WV_snowfall_2024.csv', index=False)

In [20]:
frame

         GHCN ID          Date     Station
0    USC00468308  Station Name    SNOWSHOE
1    USC00468308  Station Name    SNOWSHOE
2    USC00468308  Station Name    SNOWSHOE
3    USC00468308  Station Name    SNOWSHOE
4    USC00468308  Station Name    SNOWSHOE
5    USC00468308        County  POCAHONTAS
6    USC00468308        County  POCAHONTAS
7    USC00468308        County  POCAHONTAS
8    USC00468308        County  POCAHONTAS
9    USC00468308        County  POCAHONTAS
10   USC00468308         State          WV
11   USC00468308         State          WV
12   USC00468308         State          WV
13   USC00468308         State          WV
14   USC00468308         State          WV
15   USC00468308     Elevation        4801
16   USC00468308     Elevation        4801
17   USC00468308     Elevation        4801
18   USC00468308     Elevation        4801
19   USC00468308     Elevation        4801
20   USC00468308      Latitude        38.4
21   USC00468308      Latitude        38.4
22   USC00468308      Latitude        38.4
23   USC00468308      Latitude        38.4
24   USC00468308      Latitude        38.4
25   USC00468308     Longitude       -80.0
26   USC00468308     Longitude       -80.0
27   USC00468308     Longitude       -80.0
28   USC00468308     Longitude       -80.0
29   USC00468308     Longitude       -80.0
30   USC00468308         Nov 1           0
31   USC00468308         Nov 1         NaN
32   USC00468308         Nov 1         NaN
33   USC00468308         Nov 1         NaN
34   USC00468308         Nov 1         NaN
35   USC00468308         Nov 2           0
36   USC00468308         Nov 2         NaN
37   USC00468308         Nov 2         NaN
38   USC00468308         Nov 2         NaN
39   USC00468308         Nov 2         NaN
40   USC00468308         Nov 3           0
41   USC00468308         Nov 3         NaN
42   USC00468308         Nov 3         NaN
43   USC00468308         Nov 3         NaN
44   USC00468308         Nov 3         NaN
45   USC00468308         Nov 4           0
46   USC00468308         Nov 4         NaN
47   USC00468308         Nov 4         NaN
48   USC00468308         Nov 4         NaN
49   USC00468308         Nov 4         NaN
50   USC00468308         Nov 5           0
51   USC00468308         Nov 5         NaN
52   USC00468308         Nov 5         NaN
53   USC00468308         Nov 5         NaN
54   USC00468308         Nov 5         NaN
55   USC00468308         Nov 6           0
56   USC00468308         Nov 6         NaN
57   USC00468308         Nov 6         NaN
58   USC00468308         Nov 6         NaN
59   USC00468308         Nov 6         NaN
60   USC00468308         Nov 7           0
61   USC00468308         Nov 7         NaN
62   USC00468308         Nov 7         NaN
63   USC00468308         Nov 7         NaN
64   USC00468308         Nov 7         NaN
65   USC00468308         Nov 8           0
66   USC00468308         Nov 8         NaN
67   USC00468308         Nov 8         NaN
68   USC00468308         Nov 8         NaN
69   USC00468308         Nov 8         NaN
70   USC00468308         Nov 9           0
71   USC00468308         Nov 9         NaN
72   USC00468308         Nov 9         NaN
73   USC00468308         Nov 9         NaN
74   USC00468308         Nov 9         NaN
75   USC00468308        Nov 10           0
76   USC00468308        Nov 10         NaN
77   USC00468308        Nov 10         NaN
78   USC00468308        Nov 10         NaN
79   USC00468308        Nov 10         NaN
80   USC00468308        Nov 11           0
81   USC00468308        Nov 11         NaN
82   USC00468308        Nov 11         NaN
83   USC00468308        Nov 11         NaN
84   USC00468308        Nov 11         NaN
85   USC00468308        Nov 12           0
86   USC00468308        Nov 12         NaN
87   USC00468308        Nov 12         NaN
88   USC00468308        Nov 12         NaN
89   USC00468308        Nov 12         NaN
90   USC00468308        Nov 13           0
91   USC00468308        Nov 13         NaN
92   USC00468308        Nov 13         NaN
93   USC00468308        Nov 13         NaN
94   USC00468308        Nov 13         NaN
95   USC00468308        Nov 14           0
96   USC00468308        Nov 14         NaN
97   USC00468308        Nov 14         NaN
98   USC00468308        Nov 14         NaN
99   USC00468308        Nov 14         NaN
100  USC00468308        Nov 15           0
101  USC00468308        Nov 15         NaN
102  USC00468308        Nov 15         NaN
103  USC00468308        Nov 15         NaN
104  USC00468308        Nov 15         NaN
105  USC00468308        Nov 16           0
106  USC00468308        Nov 16         NaN
107  USC00468308        Nov 16         NaN
108  USC00468308        Nov 16         NaN
109  USC00468308        Nov 16         NaN
110  USC00468308        Nov 17           0
111  USC00468308        Nov 17         NaN
112  USC00468308        Nov 17         NaN
113  USC00468308        Nov 17         NaN
114  USC00468308        Nov 17         NaN
115  USC00468308        Nov 18           0
116  USC00468308        Nov 18         NaN
117  USC00468308        Nov 18         NaN
118  USC00468308        Nov 18         NaN
119  USC00468308        Nov 18         NaN
120  USC00468308        Nov 19           0
121  USC00468308        Nov 19         NaN
122  USC00468308        Nov 19         NaN
123  USC00468308        Nov 19         NaN
124  USC00468308        Nov 19         NaN
125  USC00468308        Nov 20           0
126  USC00468308        Nov 20         NaN
127  USC00468308        Nov 20         NaN
128  USC00468308        Nov 20         NaN
129  USC00468308        Nov 20         NaN
130  USC00468308        Nov 21           0
131  USC00468308        Nov 21         NaN
132  USC00468308        Nov 21         NaN
133  USC00468308        Nov 21         NaN
134  USC00468308        Nov 21         NaN
135  USC00468308        Nov 22         3.8
136  USC00468308        Nov 22         NaN
137  USC00468308        Nov 22         NaN
138  USC00468308        Nov 22         NaN
139  USC00468308        Nov 22         NaN
140  USC00468308        Nov 23         6.3
141  USC00468308        Nov 23         NaN
142  USC00468308        Nov 23         NaN
143  USC00468308        Nov 23         NaN
144  USC00468308        Nov 23         NaN
145  USC00468308        Nov 24           0
146  USC00468308        Nov 24         NaN
147  USC00468308        Nov 24         NaN
148  USC00468308        Nov 24         NaN
149  USC00468308        Nov 24         NaN
150  USC00468308        Nov 25           0
151  USC00468308        Nov 25         NaN
152  USC00468308        Nov 25         NaN
153  USC00468308        Nov 25         NaN
154  USC00468308        Nov 25         NaN
155  USC00468308        Nov 26           0
156  USC00468308        Nov 26         NaN
157  USC00468308        Nov 26         NaN
158  USC00468308        Nov 26         NaN
159  USC00468308        Nov 26         NaN
160  USC00468308        Nov 27           0
161  USC00468308        Nov 27         NaN
162  USC00468308        Nov 27         NaN
163  USC00468308        Nov 27         NaN
164  USC00468308        Nov 27         NaN
165  USC00468308        Nov 28           0
166  USC00468308        Nov 28         NaN
167  USC00468308        Nov 28         NaN
168  USC00468308        Nov 28         NaN
169  USC00468308        Nov 28         NaN
170  USC00468308        Nov 29         2.8
171  USC00468308        Nov 29         NaN
172  USC00468308        Nov 29         NaN
173  USC00468308        Nov 29         NaN
174  USC00468308        Nov 29         NaN
175  USC00468308        Nov 30         1.6
176  USC00468308        Nov 30         NaN
177  USC00468308        Nov 30         NaN
178  USC00468308        Nov 30         NaN
179  USC00468308        Nov 30         NaN
180  USC00468308         Dec 1         NaN
181  USC00468308         Dec 1           4
182  USC00468308         Dec 1         NaN
183  USC00468308         Dec 1         NaN
184  USC00468308         Dec 1         NaN
185  USC00468308         Dec 2         NaN
186  USC00468308         Dec 2           1
187  USC00468308         Dec 2         NaN
188  USC00468308         Dec 2         NaN
189  USC00468308         Dec 2         NaN
190  USC00468308         Dec 3         NaN
191  USC00468308         Dec 3           1
192  USC00468308         Dec 3         NaN
193  USC00468308         Dec 3         NaN
194  USC00468308         Dec 3         NaN
195  USC00468308         Dec 4         NaN
196  USC00468308         Dec 4           0
197  USC00468308         Dec 4         NaN
198  USC00468308         Dec 4         NaN
199  USC00468308         Dec 4         NaN
200  USC00468308         Dec 5         NaN
201  USC00468308         Dec 5         2.5
202  USC00468308         Dec 5         NaN
203  USC00468308         Dec 5         NaN
204  USC00468308         Dec 5         NaN
205  USC00468308         Dec 6         NaN
206  USC00468308         Dec 6           1
207  USC00468308         Dec 6         NaN
208  USC00468308         Dec 6         NaN
209  USC00468308         Dec 6         NaN
210  USC00468308         Dec 7         NaN
211  USC00468308         Dec 7         0.5
212  USC00468308         Dec 7         NaN
213  USC00468308         Dec 7         NaN
214  USC00468308         Dec 7         NaN
215  USC00468308         Dec 8         NaN
216  USC00468308         Dec 8           0
217  USC00468308         Dec 8         NaN
218  USC00468308         Dec 8         NaN
219  USC00468308         Dec 8         NaN
220  USC00468308         Dec 9         NaN
221  USC00468308         Dec 9           M
222  USC00468308         Dec 9         NaN
223  USC00468308         Dec 9         NaN
224  USC00468308         Dec 9         NaN
225  USC00468308        Dec 10         NaN
226  USC00468308        Dec 10           M
227  USC00468308        Dec 10         NaN
228  USC00468308        Dec 10         NaN
229  USC00468308        Dec 10         NaN
230  USC00468308        Dec 11         NaN
231  USC00468308        Dec 11           M
232  USC00468308        Dec 11         NaN
233  USC00468308        Dec 11         NaN
234  USC00468308        Dec 11         NaN
235  USC00468308        Dec 12         NaN
236  USC00468308        Dec 12         3.8
237  USC00468308        Dec 12         NaN
238  USC00468308        Dec 12         NaN
239  USC00468308        Dec 12         NaN
240  USC00468308        Dec 13         NaN
241  USC00468308        Dec 13           M
242  USC00468308        Dec 13         NaN
243  USC00468308        Dec 13         NaN
244  USC00468308        Dec 13         NaN
245  USC00468308        Dec 14         NaN
246  USC00468308        Dec 14           0
247  USC00468308        Dec 14         NaN
248  USC00468308        Dec 14         NaN
249  USC00468308        Dec 14         NaN
250  USC00468308        Dec 15         NaN
251  USC00468308        Dec 15           M
252  USC00468308        Dec 15         NaN
253  USC00468308        Dec 15         NaN
254  USC00468308        Dec 15         NaN
255  USC00468308        Dec 16         NaN
256  USC00468308        Dec 16           4
257  USC00468308        Dec 16         NaN
258  USC00468308        Dec 16         NaN
259  USC00468308        Dec 16         NaN
260  USC00468308        Dec 17         NaN
261  USC00468308        Dec 17           M
262  USC00468308        Dec 17         NaN
263  USC00468308        Dec 17         NaN
264  USC00468308        Dec 17         NaN
265  USC00468308        Dec 18         NaN
266  USC00468308        Dec 18           M
267  USC00468308        Dec 18         NaN
268  USC00468308        Dec 18         NaN
269  USC00468308        Dec 18         NaN
270  USC00468308        Dec 19         NaN
271  USC00468308        Dec 19           M
272  USC00468308        Dec 19         NaN
273  USC00468308        Dec 19         NaN
274  USC00468308        Dec 19         NaN
275  USC00468308        Dec 20         NaN
276  USC00468308        Dec 20           1
277  USC00468308        Dec 20         NaN
278  USC00468308        Dec 20         NaN
279  USC00468308        Dec 20         NaN
280  USC00468308        Dec 21         NaN
281  USC00468308        Dec 21         2.1
282  USC00468308        Dec 21         NaN
283  USC00468308        Dec 21         NaN
284  USC00468308        Dec 21         NaN
285  USC00468308        Dec 22         NaN
286  USC00468308        Dec 22         3.1
287  USC00468308        Dec 22         NaN
288  USC00468308        Dec 22         NaN
289  USC00468308        Dec 22         NaN
290  USC00468308        Dec 23         NaN
291  USC00468308        Dec 23           0
292  USC00468308        Dec 23         NaN
293  USC00468308        Dec 23         NaN
294  USC00468308        Dec 23         NaN
295  USC00468308        Dec 24         NaN
296  USC00468308        Dec 24           0
297  USC00468308        Dec 24         NaN
298  USC00468308        Dec 24         NaN
299  USC00468308        Dec 24         NaN
300  USC00468308        Dec 25         NaN
301  USC00468308        Dec 25           M
302  USC00468308        Dec 25         NaN
303  USC00468308        Dec 25         NaN
304  USC00468308        Dec 25         NaN
305  USC00468308        Dec 26         NaN
306  USC00468308        Dec 26           M
307  USC00468308        Dec 26         NaN
308  USC00468308        Dec 26         NaN
309  USC00468308        Dec 26         NaN
310  USC00468308        Dec 27         NaN
311  USC00468308        Dec 27           M
312  USC00468308        Dec 27         NaN
313  USC00468308        Dec 27         NaN
314  USC00468308        Dec 27         NaN
315  USC00468308        Dec 28         NaN
316  USC00468308        Dec 28           M
317  USC00468308        Dec 28         NaN
318  USC00468308        Dec 28         NaN
319  USC00468308        Dec 28         NaN
320  USC00468308        Dec 29         NaN
321  USC00468308        Dec 29           M
322  USC00468308        Dec 29         NaN
323  USC00468308        Dec 29         NaN
324  USC00468308        Dec 29         NaN
325  USC00468308        Dec 30         NaN
326  USC00468308        Dec 30           M
327  USC00468308        Dec 30         NaN
328  USC00468308        Dec 30         NaN
329  USC00468308        Dec 30         NaN
330  USC00468308        Dec 31         NaN
331  USC00468308        Dec 31           M
332  USC00468308        Dec 31         NaN
333  USC00468308        Dec 31         NaN
334  USC00468308        Dec 31         NaN
335  USC00468308         Jan 1         NaN
336  USC00468308         Jan 1         NaN
337  USC00468308         Jan 1         2.7
338  USC00468308         Jan 1         NaN
339  USC00468308         Jan 1         NaN
340  USC00468308         Jan 2         NaN
341  USC00468308         Jan 2         NaN
342  USC00468308         Jan 2         2.5
343  USC00468308         Jan 2         NaN
344  USC00468308         Jan 2         NaN
345  USC00468308         Jan 3         NaN
346  USC00468308         Jan 3         NaN
347  USC00468308         Jan 3           1
348  USC00468308         Jan 3         NaN
349  USC00468308         Jan 3         NaN
350  USC00468308         Jan 4         NaN
351  USC00468308         Jan 4         NaN
352  USC00468308         Jan 4           2
353  USC00468308         Jan 4         NaN
354  USC00468308         Jan 4         NaN
355  USC00468308         Jan 5         NaN
356  USC00468308         Jan 5         NaN
357  USC00468308         Jan 5           0
358  USC00468308         Jan 5         NaN
359  USC00468308         Jan 5         NaN
360  USC00468308         Jan 6         NaN
361  USC00468308         Jan 6         NaN
362  USC00468308         Jan 6         6.6
363  USC00468308         Jan 6         NaN
364  USC00468308         Jan 6         NaN
365  USC00468308         Jan 7         NaN
366  USC00468308         Jan 7         NaN
367  USC00468308         Jan 7         3.7
368  USC00468308         Jan 7         NaN
369  USC00468308         Jan 7         NaN
370  USC00468308         Jan 8         NaN
371  USC00468308         Jan 8         NaN
372  USC00468308         Jan 8           2
373  USC00468308         Jan 8         NaN
374  USC00468308         Jan 8         NaN
375  USC00468308         Jan 9         NaN
376  USC00468308         Jan 9         NaN
377  USC00468308         Jan 9           4
378  USC00468308         Jan 9         NaN
379  USC00468308         Jan 9         NaN
380  USC00468308        Jan 10         NaN
381  USC00468308        Jan 10         NaN
382  USC00468308        Jan 10         1.2
383  USC00468308        Jan 10         NaN
384  USC00468308        Jan 10         NaN
385  USC00468308        Jan 11         NaN
386  USC00468308        Jan 11         NaN
387  USC00468308        Jan 11           3
388  USC00468308        Jan 11         NaN
389  USC00468308        Jan 11         NaN
390  USC00468308        Jan 12         NaN
391  USC00468308        Jan 12         NaN
392  USC00468308        Jan 12           6
393  USC00468308        Jan 12         NaN
394  USC00468308        Jan 12         NaN
395  USC00468308        Jan 13         NaN
396  USC00468308        Jan 13         NaN
397  USC00468308        Jan 13           T
398  USC00468308        Jan 13         NaN
399  USC00468308        Jan 13         NaN
400  USC00468308        Jan 14         NaN
401  USC00468308        Jan 14         NaN
402  USC00468308        Jan 14           0
403  USC00468308        Jan 14         NaN
404  USC00468308        Jan 14         NaN
405  USC00468308        Jan 15         NaN
406  USC00468308        Jan 15         NaN
407  USC00468308        Jan 15           1
408  USC00468308        Jan 15         NaN
409  USC00468308        Jan 15         NaN
410  USC00468308        Jan 16         NaN
411  USC00468308        Jan 16         NaN
412  USC00468308        Jan 16           0
413  USC00468308        Jan 16         NaN
414  USC00468308        Jan 16         NaN
415  USC00468308        Jan 17         NaN
416  USC00468308        Jan 17         NaN
417  USC00468308        Jan 17           2
418  USC00468308        Jan 17         NaN
419  USC00468308        Jan 17         NaN
420  USC00468308        Jan 18         NaN
421  USC00468308        Jan 18         NaN
422  USC00468308        Jan 18           0
423  USC00468308        Jan 18         NaN
424  USC00468308        Jan 18         NaN
425  USC00468308        Jan 19         NaN
426  USC00468308        Jan 19         NaN
427  USC00468308        Jan 19           1
428  USC00468308        Jan 19         NaN
429  USC00468308        Jan 19         NaN
430  USC00468308        Jan 20         NaN
431  USC00468308        Jan 20         NaN
432  USC00468308        Jan 20           6
433  USC00468308        Jan 20         NaN
434  USC00468308        Jan 20         NaN
435  USC00468308        Jan 21         NaN
436  USC00468308        Jan 21         NaN
437  USC00468308        Jan 21         0.5
438  USC00468308        Jan 21         NaN
439  USC00468308        Jan 21         NaN
440  USC00468308        Jan 22         NaN
441  USC00468308        Jan 22         NaN
442  USC00468308        Jan 22           0
443  USC00468308        Jan 22         NaN
444  USC00468308        Jan 22         NaN
445  USC00468308        Jan 23         NaN
446  USC00468308        Jan 23         NaN
447  USC00468308        Jan 23           0
448  USC00468308        Jan 23         NaN
449  USC00468308        Jan 23         NaN
450  USC00468308        Jan 24         NaN
451  USC00468308        Jan 24         NaN
452  USC00468308        Jan 24           1
453  USC00468308        Jan 24         NaN
454  USC00468308        Jan 24         NaN
455  USC00468308        Jan 25         NaN
456  USC00468308        Jan 25         NaN
457  USC00468308        Jan 25           0
458  USC00468308        Jan 25         NaN
459  USC00468308        Jan 25         NaN
460  USC00468308        Jan 26         NaN
461  USC00468308        Jan 26         NaN
462  USC00468308        Jan 26           0
463  USC00468308        Jan 26         NaN

In [406]:
li

[         GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
          GHCN ID Station Name      County State  Elevation  Latitude  \
 103  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

      Longitude Nov 1 Nov 2 Nov 3  ... Nov 21 Nov 22 Nov 23 Nov 24 Nov 25  \
 103      -80.0     0     0     0  ...      0    3.8    6.3      0      0

     Nov 26 Nov 27 Nov 28 Nov 29 Nov 30
 103      0      0      0    2.8    1.6

 [1 rows x 37 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],
         GHCN ID Station Name      County State  Elevation  Latitude  \
 92  USC00468308     SNOWSHOE  POCAHONTAS    WV       4801      38.4

     Longitude Dec 1 Dec 2 Dec 3  ... Dec 22 Dec 23 Dec 24 Dec 25 Dec 26  \
 92      -80.0     4     1     1  ...    3.1      0      0      M      M

    Dec 27 Dec 28 Dec 29 Dec 30 Dec 31
 92      M      M      M      M      M

 [1 rows x 38 columns],

In [394]:
frame.columns

Index(['GHCN ID', 'Station Name', 'County', 'State', 'Elevation', 'Latitude',
       'Longitude', 'Nov 1', 'Nov 2', 'Nov 3',
       ...
       'Feb 19', 'Feb 20', 'Feb 21', 'Feb 22', 'Feb 23', 'Feb 24', 'Feb 25',
       'Feb 26', 'Feb 27', 'Feb 28'],
      dtype='object', length=127)