In [92]:
import pandas as pd

In [93]:
import glob

In [94]:
path = "C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data"

In [95]:
all_files = glob.glob(path + "/*.csv")

In [87]:
all_files

['C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_01.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_02.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_03.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_04.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_05.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_06.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_07.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_08.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_09.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_10.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_11.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_12.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_13.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_14.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_15.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_16.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_17.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_18.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_19.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_20.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_21.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_22.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_23.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_24.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_25.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_26.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_27.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_28.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_29.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_30.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_01_31.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_01.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_02.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_03.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_04.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_05.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_06.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_07.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_08.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_09.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_10.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_11.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_12.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_13.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_14.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_15.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_16.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_17.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_18.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_19.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_20.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_21.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_22.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_23.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_24.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_25.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_26.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_27.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_02_28.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_01.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_02.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_03.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_04.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_05.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_06.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_07.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_08.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_09.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_10.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_11.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_12.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_13.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_14.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_15.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_16.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_17.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_18.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_19.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_20.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_21.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_22.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_23.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_24.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_25.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_26.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_27.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_28.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_29.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_30.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_03_31.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_01.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_02.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_03.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_04.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_05.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_06.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_07.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_08.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_09.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_10.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_11.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_12.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_13.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_14.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_15.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_16.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_17.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_18.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_19.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_20.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_21.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_22.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_23.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_24.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_25.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_04_26.csv',
 'C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data\\West_Virginia_Snowfall_Data_2014_12_13.csv']

In [96]:
li = []

In [97]:
for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0, comment="#")
    li.append(df)

In [98]:
frame = pd.concat(li, axis = 0, ignore_index=True)

In [91]:
print(li)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [37]:
df = pd.read_csv("C:/Users/spenc/OneDrive/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data/West_Virginia_Snowfall_Data_2014_01_01.csv", sep=",", comment="#")

In [39]:
df.iloc[99]

GHCN ID         USC00468308
Station Name       SNOWSHOE
County           POCAHONTAS
State                    WV
Elevation              4846
Latitude               38.4
Longitude            -79.99
Jan 1                     0
Jan 2                     0
Jan 3                     0
Jan 4                     0
Jan 5                     1
Jan 6                   0.1
Jan 7                     3
Jan 8                     3
Jan 9                     T
Jan 10                    1
Jan 11                    0
Jan 12                    0
Jan 13                    0
Jan 14                    T
Jan 15                    T
Jan 16                    T
Jan 17                    T
Jan 18                    0
Jan 19                    2
Jan 20                    0
Jan 21                    1
Jan 22                    1
Jan 23                    0
Jan 24                    4
Jan 25                    1
Jan 26                    3
Jan 27                    3
Jan 28                    2
Jan 29                    T
Jan 30                    2
Jan 31                    3
Name: 99, dtype: object

In [40]:
df[df["Station Name"] == "SNOWSHOE"]

,GHCN ID,Station Name,County,State,Elevation,Latitude,Longitude,Jan 1,Jan 2,Jan 3,Jan 4,Jan 5,Jan 6,Jan 7,Jan 8,Jan 9,Jan 10,Jan 11,Jan 12,Jan 13,Jan 14,Jan 15,Jan 16,Jan 17,Jan 18,Jan 19,Jan 20,Jan 21,Jan 22,Jan 23,Jan 24,Jan 25,Jan 26,Jan 27,Jan 28,Jan 29,Jan 30,Jan 31
99,USC00468308,SNOWSHOE,POCAHONTAS,WV,4846,38.4,-79.99,0,0,0,0,1,0.1,3,3,T,1,0,0,0,T,T,T,T,0,2,0,1,1,0,4,1,3,3,2,T,2,3

In [44]:
print(df.loc[df["Station Name"] == "SNOWSHOE"].index)

Index([99], dtype='int64')

In [10]:
import pandas as pd

In [11]:
import glob

In [12]:
path = "C:/Users/Spencer Woo/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data/Daily_Snow_Observations_Data_2024"

In [13]:
all_files = glob.glob(path + "/*.csv")

In [14]:
li = []

In [24]:
for filename in all_files:
    df = pd.read_csv(filename, comment="#", index_col=None, header=0, sep=',', on_bad_lines='skip')
    li.append(df[df["Station Name"] == "SNOWSHOE"])

ParserError: Error tokenizing data. C error: Expected 1 fields in line 9, saw 2

In [14]:
frame = pd.concat(li, axis=0, ignore_index=True)

In [15]:
frame

,GHCN ID,Station Name,County,State,Elevation,Latitude,Longitude,Nov 1,Nov 2,Nov 3,...,Feb 19,Feb 20,Feb 21,Feb 22,Feb 23,Feb 24,Feb 25,Feb 26,Feb 27,Feb 28
0,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,1,2,2,0,0,0,0,0,0,2
115,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,1,2,2,0,0,0,0,0,0,2
116,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,1,2,2,0,0,0,0,0,0,2
117,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,1,2,2,0,0,0,0,0,0,2
118,USC00468308,SNOWSHOE,POCAHONTAS,WV,4801,38.4,-80.0,NaN,NaN,NaN,...,1,2,2,0,0,0,0,0,0,2

In [16]:
frame.to_csv('C:/Users/Spencer Woo/Desktop/01_SNOW_Snowshoe_West_Virginia_Snowfall_Data/pocahontas_county_WV_snowfall_2024.csv', index=False)

In [ ]:
filtered_columns = frame.filter(items=[])

In [ ]:
# Wet Bulb Temperature

#The threshold for snowmaking conditions exists on a curve. The best conditions are low temperature and low relative humidity. 
#Snowmaking can occur at temperatures as high as 6 degrees Celsius but for this to happen, there cannot be humidity. 
#this conditional statement will capture best to marginal conditions (inclusive) for snowmaking.

In [ ]:
if (temperature <= 6 and humidity == 0
    
or temperature <= 5 and humidity <= 10

or temperature <= 3 and humidity <= 20

or temperature <= 2 and humidity <= 30

or temperature <= 1 and humidity <= 40

or temperature <= 0 and humidity <= 50

or temperature <= -1 and humidity <= 60

or temperature <= -2 and humidity <= 90

or temperature <= -3 and humidity <= 100)
{}

In [ ]:
# Electricity Budget

# Snowshoe's electricity is provided by Potomac Edison
# different quote for non-residential
# First 400 kWh: $0.12808/kWh 
# Additional kWh: $0.11403/kWh 
# Snowshoe Mountain's snowmaking team posesses 75 fixed position tower fan guns and 90 low-energy stick guns.
# The fixed position fan guns are DemacLenko